// Estradas icônicas do mototurismo brasileiro — conteúdo editorial pro cluster /estradas.
// Fatos mantidos gerais/aproximados de propósito ("cerca de", "trecho de serra") pra não cravar número incerto.
export const ESTRADAS = [
  {
    slug: 'serra-do-rio-do-rastro',
    nome: 'Serra do Rio do Rastro',
    uf: ['sc'],
    regiao: 'Serra Geral · Santa Catarina',
    rodovia: 'SC-390 / SC-438',
    pontas: 'Bom Jardim da Serra ↔ Lauro Müller',
    piso: 'Asfalto',
    dificuldade: 'Exige atenção — curvas fechadas em sequência',
    melhorEpoca: 'Abril a novembro (inverno traz neblina e frio intenso no topo)',
    resumo: 'A subida de serra mais famosa do Brasil pra quem roda de moto: dezenas de curvas em ferradura encravadas no paredão da Serra Geral, com mirante a mais de 1.400 m.',
    descricao: [
      'A Serra do Rio do Rastro é o paredão mais cobiçado do mototurismo nacional. Em poucos quilômetros a estrada despenca (ou sobe) o costão da Serra Geral numa sucessão de curvas em ferradura que viraram cartão-postal — dá pra ver boa parte do traçado de uma vez só do mirante lá de cima.',
      'O topo passa de 1.400 m de altitude e o clima muda rápido: é comum sair do calor lá embaixo, em Lauro Müller, e chegar na neblina gelada em Bom Jardim da Serra. No inverno aparece geada e, em anos raros, neve. Capriche na roupa térmica e no respeito ao asfalto molhado.',
      'O traçado pede moto bem de freio e piloto descansado. Não é trecho pra pressa: a graça está em rodar com calma, parar nos mirantes e fotografar. Vários fotógrafos de estrada trabalham nas curvas — vale a foto subindo a serra.',
    ],
    destaques: ['Mirante do topo (vista de todas as curvas)', 'Paredão da Serra Geral', 'Clima de montanha — frio e neblina', 'Curvas em ferradura em sequência'],
    faqs: [
      { q: 'Onde fica a Serra do Rio do Rastro?', a: 'Em Santa Catarina, ligando Bom Jardim da Serra (no alto) a Lauro Müller (embaixo), pela SC-390. É parte da Serra Geral, no sul do estado.' },
      { q: 'Qual a melhor época pra ir de moto na Serra do Rio do Rastro?', a: 'De abril a novembro o tempo costuma render mais. No inverno o frio e a neblina no topo são intensos — lindo, mas exige roupa térmica e cuidado com asfalto molhado e geada.' },
      { q: 'A Serra do Rio do Rastro é perigosa de moto?', a: 'Não é difícil tecnicamente, mas são curvas fechadas em sequência com despenhadeiro ao lado. Vá com calma, freios em dia e sem disputar. A graça é rodar tranquilo e curtir a vista.' },
    ],
  },
  {
    slug: 'estrada-da-graciosa',
    nome: 'Estrada da Graciosa',
    uf: ['pr'],
    regiao: 'Mata Atlântica · Paraná',
    rodovia: 'PR-410',
    pontas: 'Quatro Barras / Curitiba ↔ Morretes',
    piso: 'Asfalto e trechos de paralelepípedo histórico',
    dificuldade: 'Moderada — piso irregular e umidade',
    melhorEpoca: 'O ano todo; manhãs secas evitam o piso escorregadio',
    resumo: 'Estrada histórica que desce a Serra do Mar paranaense em meio à Mata Atlântica, com trechos de paralelepípedo, recantos e cachoeiras até Morretes.',
    descricao: [
      'A Graciosa liga a região de Curitiba ao litoral em Morretes atravessando a Serra do Mar dentro da Mata Atlântica preservada. É uma das estradas mais antigas e charmosas do país, com trechos de paralelepípedo, pontes de pedra e recantos de descanso à sombra da floresta.',
      'O piso irregular e a umidade constante da mata pedem cautela — pedra molhada e folha no chão tiram aderência. Em compensação, é rodar devagar entre samambaias gigantes, riachos e o cheiro de mata fechada.',
      'O destino clássico é Morretes, com o famoso barreado e o centrinho histórico. Muita gente fecha o passeio descendo a Graciosa e voltando pela BR-277, ou vice-versa.',
    ],
    destaques: ['Mata Atlântica preservada', 'Paralelepípedo histórico', 'Recantos e cachoeiras', 'Barreado em Morretes'],
    faqs: [
      { q: 'Onde fica a Estrada da Graciosa?', a: 'No Paraná, pela PR-410, ligando a região de Quatro Barras/Curitiba ao litoral em Morretes, atravessando a Serra do Mar.' },
      { q: 'Dá pra ir de moto de rua na Graciosa?', a: 'Dá. Há trechos de asfalto e trechos de paralelepípedo histórico — qualquer moto roda, mas o piso irregular e úmido pede velocidade baixa e atenção, ainda mais com chuva.' },
    ],
  },
  {
    slug: 'serra-do-corvo-branco',
    nome: 'Serra do Corvo Branco',
    uf: ['sc'],
    regiao: 'Serra Catarinense · Santa Catarina',
    rodovia: 'SC-390',
    pontas: 'Urubici ↔ Grão-Pará',
    piso: 'Asfalto',
    dificuldade: 'Moderada — altitude e neblina',
    melhorEpoca: 'Outono e inverno pelo friozinho de serra; verão pelo verde',
    resumo: 'Desfiladeiro escavado na rocha perto de Urubici, com paredões de pedra de dezenas de metros e uma das paisagens mais imponentes da serra catarinense.',
    descricao: [
      'A Serra do Corvo Branco é marcada pelo desfiladeiro escavado na rocha viva: a estrada corta um paredão de pedra altíssimo, criando um corredor dramático que é parada obrigatória pra foto. Fica nos arredores de Urubici, polo do friozinho catarinense.',
      'A região reúne Urubici, Bom Jardim da Serra e a própria Serra do Rio do Rastro num raio rodável de moto — dá pra encadear várias serras no mesmo roteiro. Altitude alta significa clima de montanha: neblina, frio e mudança rápida de tempo.',
      'Combine com a Cascata do Avencal, a Pedra Furada e os campos de altitude de Urubici. É um dos melhores polos de base pra quem quer rodar a serra catarinense vários dias.',
    ],
    destaques: ['Desfiladeiro escavado na rocha', 'Base em Urubici', 'Encadeia com Rio do Rastro', 'Campos de altitude'],
    faqs: [
      { q: 'Onde fica a Serra do Corvo Branco?', a: 'Em Santa Catarina, na SC-390, ligando Urubici a Grão-Pará. Fica na serra catarinense, perto de outros points como o Rio do Rastro.' },
      { q: 'Dá pra fazer Corvo Branco e Rio do Rastro na mesma viagem?', a: 'Dá, e é o roteiro clássico. Usando Urubici ou Bom Jardim da Serra como base, as duas serras ficam a uma rodada de moto uma da outra.' },
    ],
  },
  {
    slug: 'estrada-real',
    nome: 'Estrada Real',
    uf: ['mg', 'rj', 'sp'],
    regiao: 'Cidades históricas · Minas Gerais',
    rodovia: 'Rede de caminhos históricos',
    pontas: 'Diamantina · Ouro Preto · Tiradentes · Paraty',
    piso: 'Asfalto com trechos de terra/calçamento',
    dificuldade: 'Variada — depende do trecho escolhido',
    melhorEpoca: 'Outono e inverno (seca), tempo mais firme nas serras',
    resumo: 'A antiga rota do ouro que costura as cidades históricas mineiras — Ouro Preto, Tiradentes, Diamantina — em centenas de quilômetros de serra, barroco e gastronomia.',
    descricao: [
      'A Estrada Real é uma rede de caminhos coloniais que ligava as minas de ouro e diamante ao litoral. Hoje vira roteiro de moto entre cidades históricas como Ouro Preto, Mariana, Tiradentes, São João del-Rei e Diamantina, com igrejas barrocas, ladeiras de pedra e comida mineira.',
      'Não é uma estrada única: são vários trechos (Caminho Velho, Caminho Novo, Caminho dos Diamantes) que dá pra montar conforme o tempo. A maioria é asfalto de serra com curvas, intercalado por trechos de terra e calçamento nos centros históricos.',
      'É roteiro de vários dias e de pousar nas cidades. Mototurismo aqui é tanto estrada quanto cultura: vale reservar tempo pra museus, igrejas e fogão a lenha.',
    ],
    destaques: ['Cidades históricas e barroco', 'Gastronomia mineira', 'Vários trechos (Velho, Novo, Diamantes)', 'Roteiro de múltiplos dias'],
    faqs: [
      { q: 'O que é a Estrada Real?', a: 'É a antiga rota do ouro e dos diamantes do período colonial, hoje um roteiro turístico que liga cidades históricas de Minas Gerais ao Rio de Janeiro e a Paraty (SP/RJ).' },
      { q: 'Quantos dias leva pra fazer a Estrada Real de moto?', a: 'Depende do trecho. Dá pra fazer um fim de semana entre algumas cidades ou uma viagem de uma semana ou mais cobrindo Diamantes, Velho e Novo. É roteiro de pousar nas cidades.' },
    ],
  },
  {
    slug: 'serra-da-mantiqueira',
    nome: 'Serra da Mantiqueira',
    uf: ['mg', 'sp', 'rj'],
    regiao: 'Montanhas · MG / SP / RJ',
    rodovia: 'Diversas (SP-050, rodovias de serra)',
    pontas: 'Campos do Jordão · Gonçalves · Monte Verde',
    piso: 'Asfalto, alguns trechos de terra entre vilas',
    dificuldade: 'Moderada — curvas de serra e altitude',
    melhorEpoca: 'Outono e inverno pelo friozinho; primavera pelo verde',
    resumo: 'Cadeia de montanhas entre MG, SP e RJ com clima de serra, vilas charmosas e curvas — Campos do Jordão, Gonçalves e Monte Verde são a base do mototurismo na região.',
    descricao: [
      'A Mantiqueira é a serra do friozinho mais acessível pra quem sai do eixo Rio–São Paulo–BH. Reúne destinos clássicos como Campos do Jordão, Gonçalves, Monte Verde e São Bento do Sapucaí, ligados por estradas de serra com muita curva e mirante.',
      'O traçado mistura asfalto bom em alguns trechos com estradas de terra entre as vilas — pra explorar Gonçalves e o entorno, moto trail ou big trail rende mais. O clima de altitude pede roupa pra frio mesmo no verão.',
      'É um dos polos onde a comunidade Pistaviva mais tem parada cadastrada: pousadas, restaurantes e mirantes amigos do motociclista. Bom destino pra fim de semana ou bate-volta saindo das capitais.',
    ],
    destaques: ['Campos do Jordão e Monte Verde', 'Gonçalves e estradas de terra', 'Clima de montanha', 'Curvas e mirantes'],
    faqs: [
      { q: 'Onde fica a Serra da Mantiqueira?', a: 'É uma cadeia de montanhas entre Minas Gerais, São Paulo e Rio de Janeiro. Os polos mais rodados de moto são Campos do Jordão (SP), Gonçalves (MG) e Monte Verde (MG).' },
      { q: 'Precisa de moto trail na Mantiqueira?', a: 'Pro asfalto, qualquer moto vai. Mas pra explorar Gonçalves e as vilas por estradas de terra, uma trail ou big trail abre muito mais caminho.' },
    ],
  },
  {
    slug: 'caminho-dos-canyons',
    nome: 'Caminho dos Canyons',
    uf: ['sc', 'rs'],
    regiao: 'Canyons · divisa SC / RS',
    rodovia: 'Rodovias de serra (região de Cambará do Sul / Praia Grande)',
    pontas: 'Praia Grande ↔ Cambará do Sul',
    piso: 'Asfalto e trechos de terra',
    dificuldade: 'Moderada — serra e trechos de chão batido',
    melhorEpoca: 'Outono e inverno (céu limpo aumenta chance de ver os canyons)',
    resumo: 'Roteiro entre os grandes canyons do sul — Itaimbezinho e Fortaleza — subindo da Serra do Mar catarinense aos Campos de Cima da Serra gaúchos.',
    descricao: [
      'O Caminho dos Canyons liga Praia Grande (SC) a Cambará do Sul (RS), dando acesso aos cânions Itaimbezinho e Fortaleza — paredões de centenas de metros nos parques nacionais da região. A subida da serra é cênica e muda totalmente a paisagem em poucos quilômetros.',
      'Há trechos de asfalto e trechos de terra, dependendo do caminho escolhido entre os mirantes e parques. Big trail e trail se dão bem; moto de rua roda, mas escolha a rota pavimentada e cuidado com piso solto.',
      'O clima é de altitude: neblina pode fechar a vista dos cânions, então céu limpo (mais comum no outono/inverno) é o que se busca. Cambará do Sul é a base de hospedagem mais usada.',
    ],
    destaques: ['Cânion Itaimbezinho', 'Cânion Fortaleza', 'Campos de Cima da Serra', 'Base em Cambará do Sul'],
    faqs: [
      { q: 'Onde fica o Caminho dos Canyons?', a: 'Na divisa de Santa Catarina e Rio Grande do Sul, ligando Praia Grande (SC) a Cambará do Sul (RS), região dos parques nacionais de Aparados da Serra e Serra Geral.' },
      { q: 'Dá pra ir de moto de rua ver os canyons?', a: 'Dá, escolhendo as rotas asfaltadas, mas há bastante trecho de terra entre mirantes. Trail ou big trail rende mais e abre caminhos extras.' },
    ],
  },
  {
    slug: 'rota-do-sol-rs',
    nome: 'Rota do Sol (Tainhas)',
    uf: ['rs'],
    regiao: 'Serra gaúcha ao litoral · Rio Grande do Sul',
    rodovia: 'RS-486',
    pontas: 'Tainhas / São Francisco de Paula ↔ litoral norte (Terra de Areia)',
    piso: 'Asfalto',
    dificuldade: 'Moderada — descida de serra com curvas',
    melhorEpoca: 'Primavera e verão; cuidado com neblina na serra',
    resumo: 'A descida da serra gaúcha ao litoral pela RS-486, com a Mata Atlântica de um lado, paredões do outro e curvas que rendem foto.',
    descricao: [
      'A Rota do Sol (RS-486) liga os Campos de Cima da Serra ao litoral norte gaúcho descendo a Serra Geral em meio à Mata Atlântica. É um dos trechos mais bonitos do estado pra rodar de moto, com mirantes, vegetação fechada e curvas bem desenhadas.',
      'A descida muda o clima e a paisagem: começa no friozinho da serra e termina no calor litorâneo. Neblina é comum no alto, então atenção à visibilidade. O asfalto costuma estar em boas condições.',
      'Combina com Cambará do Sul, os cânions e a região de São Francisco de Paula, fechando um roteiro de serra gaúcha de vários dias.',
    ],
    destaques: ['Descida da Serra Geral', 'Mata Atlântica', 'Liga serra e litoral', 'Encadeia com os canyons'],
    faqs: [
      { q: 'O que é a Rota do Sol no RS?', a: 'É a RS-486, estrada que desce a serra gaúcha (região de Tainhas / São Francisco de Paula) até o litoral norte, atravessando a Serra Geral e a Mata Atlântica.' },
    ],
  },
  {
    slug: 'serra-da-canastra',
    nome: 'Serra da Canastra',
    uf: ['mg'],
    regiao: 'Cerrado de altitude · Minas Gerais',
    rodovia: 'Rodovias e estradas de terra do parque',
    pontas: 'São Roque de Minas · Sacramento · Vargem Bonita',
    piso: 'Asfalto de acesso e muita terra dentro da região',
    dificuldade: 'Alta em trechos de terra — favorece trail/big trail',
    melhorEpoca: 'Seca (maio a setembro) deixa as estradas de terra firmes',
    resumo: 'Nascente do Rio São Francisco, cachoeiras e cerrado de altitude — região de estrada de terra e queijo canastra, paraíso pra big trail.',
    descricao: [
      'A Serra da Canastra é cerrado de altitude no sudoeste mineiro, famosa pela nascente do Rio São Francisco, pela Cachoeira Casca d\'Anta e pelo queijo canastra. Boa parte da graça está nas estradas de terra que cortam o parque e as fazendas.',
      'É região que favorece moto trail e big trail: muito chão batido, poeira na seca e atoleiro na chuva. Por isso o período de seca (maio a setembro) é o mais indicado pra rodar tranquilo.',
      'São Roque de Minas é a base mais comum. Roteiro de quem curte estrada de terra, natureza e gastronomia rural — menos sobre asfalto perfeito, mais sobre aventura.',
    ],
    destaques: ['Nascente do São Francisco', 'Cachoeira Casca d\'Anta', 'Queijo canastra', 'Estradas de terra (trail)'],
    faqs: [
      { q: 'Precisa de moto trail na Serra da Canastra?', a: 'Pra explorar de verdade, sim — boa parte é estrada de terra. Moto de rua chega aos acessos asfaltados, mas trail e big trail aproveitam muito mais o parque.' },
      { q: 'Qual a melhor época pra ir à Canastra de moto?', a: 'A seca, de maio a setembro, quando as estradas de terra ficam firmes. Na chuva há atoleiro e travessias de água que complicam.' },
    ],
  },
  {
    slug: 'rota-romantica',
    nome: 'Rota Romântica',
    uf: ['rs'],
    regiao: 'Serra gaúcha · Rio Grande do Sul',
    rodovia: 'RS-235 e entorno',
    pontas: 'Nova Petrópolis · Gramado · Canela',
    piso: 'Asfalto',
    dificuldade: 'Leve a moderada',
    melhorEpoca: 'Outono/inverno pelo frio europeu; primavera pelas flores',
    resumo: 'Roteiro de colonização alemã na serra gaúcha ligando Nova Petrópolis, Gramado e Canela, com arquitetura enxaimel, gastronomia e estrada tranquila.',
    descricao: [
      'A Rota Romântica percorre a serra gaúcha por cidades de colonização alemã — Nova Petrópolis, Gramado, Canela e vizinhas — com arquitetura enxaimel, jardins, chocolate e clima europeu. É um roteiro mais leve, de curtir cidade e estrada sem pressa.',
      'O asfalto é bom e as distâncias curtas, o que torna a região ótima pra quem está começando no mototurismo ou viaja acompanhado. Inverno lota e esfria de verdade — leve roupa térmica.',
      'Combina com a Rota do Sol, os cânions e o Vale dos Vinhedos, montando uma viagem completa de serra gaúcha.',
    ],
    destaques: ['Arquitetura enxaimel', 'Gramado e Canela', 'Clima europeu', 'Roteiro leve pra começar'],
    faqs: [
      { q: 'Onde fica a Rota Romântica?', a: 'Na serra gaúcha, ligando cidades de colonização alemã como Nova Petrópolis, Gramado e Canela, pela RS-235 e estradas do entorno.' },
    ],
  },
  {
    slug: 'serra-do-cipo',
    nome: 'Serra do Cipó',
    uf: ['mg'],
    regiao: 'Cerrado e cachoeiras · Minas Gerais',
    rodovia: 'MG-010',
    pontas: 'Belo Horizonte ↔ Serra do Cipó / Conceição do Mato Dentro',
    piso: 'Asfalto, com trechos de terra nos acessos',
    dificuldade: 'Leve a moderada',
    melhorEpoca: 'Seca (abril a setembro) pra cachoeiras com água limpa e estrada firme',
    resumo: 'Saída clássica de bate-volta de BH pela MG-010, com cachoeiras, cânions e cerrado — uma das pedaladas de moto mais queridas dos mineiros.',
    descricao: [
      'A Serra do Cipó é o programa de moto preferido de muita gente de Belo Horizonte: pela MG-010 chega-se rápido a um mundo de cachoeiras, cânions e cerrado preservado, dentro e no entorno do Parque Nacional.',
      'O asfalto principal é tranquilo e cênico; os acessos a algumas cachoeiras viram terra. Dá pra fazer bate-volta de BH ou esticar até Conceição do Mato Dentro e a Cachoeira do Tabuleiro.',
      'É roteiro bom o ano todo, mas a seca deixa estradas firmes e quedas d\'água mais convidativas. Muitos restaurantes e pousadas na beira da MG-010 são amigos do motociclista.',
    ],
    destaques: ['MG-010 cênica', 'Cachoeiras e cânions', 'Bate-volta de BH', 'Cachoeira do Tabuleiro'],
    faqs: [
      { q: 'Dá pra fazer a Serra do Cipó de bate-volta de BH?', a: 'Dá, e é o programa clássico. Pela MG-010 chega-se à região em pouco tempo saindo de Belo Horizonte, dá pra ir e voltar no mesmo dia.' },
    ],
  },
  {
    slug: 'chapada-dos-veadeiros',
    nome: 'Chapada dos Veadeiros',
    uf: ['go'],
    regiao: 'Cerrado de altitude · Goiás',
    rodovia: 'GO-118 / GO-239',
    pontas: 'Brasília ↔ Alto Paraíso de Goiás · São Jorge',
    piso: 'Asfalto, com terra nos acessos às trilhas',
    dificuldade: 'Moderada — distâncias longas no cerrado',
    melhorEpoca: 'Seca (maio a setembro); na chuva os rios das trilhas enchem',
    resumo: 'Cerrado de altitude, cachoeiras e céu estrelado a algumas horas de Brasília — Alto Paraíso e São Jorge são a base pra rodar a Chapada.',
    descricao: [
      'A Chapada dos Veadeiros é cerrado de altitude no norte goiano, com cachoeiras, cânions e um dos céus mais estrelados do país. Saindo de Brasília pela GO-118, chega-se a Alto Paraíso de Goiás e São Jorge, as bases da região.',
      'As estradas de acesso são asfaltadas e cênicas, com longos trechos de cerrado aberto — atenção a combustível e distâncias. Os acessos às trilhas e cachoeiras viram terra; parte dos atrativos exige caminhada a partir do estacionamento.',
      'A seca (maio a setembro) é a melhor época: na chuva os rios das trilhas sobem e fecham atrativos. Roteiro de quem quer natureza forte e estrada de cerrado.',
    ],
    destaques: ['Cerrado de altitude', 'Cachoeiras e cânions', 'Céu estrelado', 'Base em Alto Paraíso / São Jorge'],
    faqs: [
      { q: 'Quanto tempo de moto de Brasília até a Chapada dos Veadeiros?', a: 'São algumas horas de estrada asfaltada pela GO-118 até Alto Paraíso de Goiás. Atenção às distâncias e ao combustível nos trechos de cerrado aberto.' },
    ],
  },
  {
    slug: 'alto-caparao-pico-da-bandeira',
    nome: 'Alto Caparaó — Pico da Bandeira',
    uf: ['mg', 'es'],
    regiao: 'Montanhas · divisa MG / ES',
    rodovia: 'Acessos a Alto Caparaó',
    pontas: 'Alto Caparaó (MG) · Caparaó',
    piso: 'Asfalto de acesso e terra/pedra dentro do parque',
    dificuldade: 'Alta dentro do parque — pedra solta e aclive',
    melhorEpoca: 'Seca (maio a setembro), céu aberto pra ver o pico',
    resumo: 'Base pra subir rumo ao Pico da Bandeira, um dos pontos mais altos do Brasil, na divisa de Minas e Espírito Santo.',
    descricao: [
      'Alto Caparaó é a porta de entrada do Parque Nacional do Caparaó, onde fica o Pico da Bandeira — um dos cumes mais altos do país, passando dos 2.800 m. A região de moto é montanha pura: acessos asfaltados charmosos até a vila e estradas de terra e pedra dentro do parque.',
      'A subida final ao pico é trilha de caminhada; de moto chega-se aos portões e estacionamentos por trechos de chão batido e pedra solta que favorecem trail e big trail. Frio de altitude o ano todo — pode gear de madrugada.',
      'Roteiro de natureza e altitude, bom pra encadear com a Mantiqueira e o sul do ES. A vila de Alto Caparaó concentra pousadas e apoio.',
    ],
    destaques: ['Pico da Bandeira (+2.800 m)', 'Parque Nacional do Caparaó', 'Frio de altitude', 'Trechos de terra e pedra'],
    faqs: [
      { q: 'Dá pra subir o Pico da Bandeira de moto?', a: 'Não até o cume — a parte final é trilha a pé. De moto chega-se aos portões e estacionamentos do parque por estradas de terra e pedra; trail e big trail se dão melhor.' },
    ],
  },
];

// Centro geográfico aproximado + raio (km) de cada estrada — pro bloco
// "Paradas no caminho" (proximidade via Turf). Slugs sem geo não mostram o bloco.
export const ESTRADA_GEO = {
  'serra-do-rio-do-rastro': { lat: -28.34, lng: -49.63, raio: 75 },
  'estrada-da-graciosa': { lat: -25.48, lng: -48.83, raio: 55 },
  'serra-do-corvo-branco': { lat: -28.01, lng: -49.59, raio: 60 },
  'estrada-real': { lat: -21.10, lng: -44.17, raio: 130 },
  'serra-da-mantiqueira': { lat: -22.74, lng: -45.59, raio: 90 },
  'caminho-dos-canyons': { lat: -29.05, lng: -50.15, raio: 65 },
  'rota-do-sol-rs': { lat: -29.20, lng: -50.30, raio: 80 },
  'rota-romantica': { lat: -29.37, lng: -50.88, raio: 45 },
  'serra-do-cipo': { lat: -19.30, lng: -43.60, raio: 60 },
};

export const getEstrada = (slug) => ESTRADAS.find((e) => e.slug === slug) || null;
export const allEstradaSlugs = () => ESTRADAS.map((e) => e.slug);
