import Link from 'next/link';
import Explorer from './Explorer';
import data from './data.json';
import './diamantes.css';
export const metadata = {
  title: 'Caminho dos Diamantes de moto — Mapa, terra e asfalto',
  description: 'Planeje o acesso da sua localização ao Caminho dos Diamantes. Mapa com GPX oficial, 18 etapas, notas de terra e asfalto, interdições e paradas biker.',
  alternates: { canonical: '/rotas/caminho-dos-diamantes' },
};
export default function Page() {
  return <div className="cd-page">
    <nav className="wrap cd-breadcrumb" aria-label="Trilha de navegação"><Link href="/">Início</Link><span>/</span><Link href="/rotas">Rotas</Link><span>/ Diamantes</span></nav>
    <header className="cd-hero"><div className="wrap cd-hero-grid"><div><p className="cd-kicker">Estrada Real / Minas Gerais / Caderno de rota</p><h1>Caminho dos<br /><em>Diamantes.</em></h1><p className="cd-lead">Da serra às cidades históricas. Descubra a estrada que espera por você entre Diamantina e Ouro Preto — e saiba onde o asfalto dá lugar à terra.</p><a href="#planejar" className="cd-button">Planejar minha saída ↗</a><div className="cd-stats"><div><strong>395 <small>km</small></strong><span>referência oficial</span></div><div><strong>18</strong><span>etapas para explorar</span></div><div><strong>MG</strong><span>Diamantina ↔ Ouro Preto</span></div></div></div><figure className="cd-reference"><img src="/rotas/diamantes-referencia.gif" alt="Mapa esquemático da Estrada Real, destacando Diamantina e Ouro Preto; Rio e Paraty pertencem a outros caminhos." width="246" height="396" /><figcaption>Mapa esquemático do Instituto Estrada Real.<br />Referência visual; navegação no mapa abaixo.</figcaption></figure></div></header>
    <div className="wrap"><aside className="cd-alert"><strong>Antes de seguir: interdição informada na fonte oficial</strong><p>O Instituto mantém aviso para Santa Rita Durão–Mariana e indica alternativa pela MG-129 para carros. Confirme as condições e a passagem de motos antes de sair. O GPX histórico inclui o setor afetado; sua presença no mapa não significa acesso liberado.</p><a href={data.source} target="_blank" rel="noopener noreferrer">Consultar aviso e alternativas ↗</a></aside>
      <section className="cd-overview" aria-label="Distribuição de piso"><div><p className="cd-kicker">O terreno faz parte da viagem</p><h2>Prepare-se para a terra.</h2></div><div><div className="cd-surface-bar" aria-hidden="true"><span /><span /><span /></div><p><strong>73,5% terra</strong> · 26% asfalto · 0,5% trilha</p><p className="cd-small">Percentuais publicados pelo Instituto. Referência histórica, não levantamento em tempo real. Quilometragens e percentuais da fonte apresentam diferenças de arredondamento.</p></div></section>
      <Explorer />
      <section className="cd-bikers" aria-labelledby="bikers-title"><div><p className="cd-kicker">03 / Uma parada pelo encontro</p><h2 id="bikers-title">O cumprimento biker<br />também entra na viagem.</h2><p>A Rota Biker reúne monumentos e pontos de encontro. No Caminho dos Diamantes, o catálogo cita o Bela Vista Mall, em Conceição do Mato Dentro.</p><p>Confira funcionamento, endereço e disponibilidade de carimbo com o local. A rede diferencia monumentos prontos, em implantação e em construção.</p><a className="cd-text-link" href="https://monumentobikers.com.br/monumentos/" target="_blank" rel="noopener noreferrer">Consultar monumentos e status oficiais ↗</a></div><div className="cd-biker-stop"><p className="cd-kicker">Parada para conferir / nº 37</p><h3>Bela Vista Mall</h3><p>Conceição do Mato Dentro · MG</p><p className="cd-small">Listagem oficial confirmada em 13/09/2026. Endereço exato, operação e carimbo precisam de confirmação; não incluídos automaticamente na rota.</p><a className="cd-button" href="https://www.google.com/maps/search/?api=1&query=Bela+Vista+Mall+Concei%C3%A7%C3%A3o+do+Mato+Dentro+MG" target="_blank" rel="noopener noreferrer">Localizar parada ↗</a><a className="cd-text-link" href="https://www.google.com/maps/d/viewer?mid=1ZHPck3Yykbhc8M1GYPrCcKf5pajiTvk" target="_blank" rel="noopener noreferrer">Abrir mapa completo da Rota Biker ↗</a></div></section>
      <section className="cd-resources"><div><p className="cd-kicker">04 / Leve o caminho com você</p><h2>Planilhas, GPX e passaporte.</h2><p>GPX oficial contém percurso histórico, inclusive trilhas e setor com aviso de interdição. Consulte alternativas antes de importar no navegador.</p><a className="cd-button" href={data.gpx} target="_blank" rel="noopener noreferrer">Abrir GPX oficial ↗</a></div><div><a href="https://institutoestradareal.com.br/passaporte/" target="_blank" rel="noopener noreferrer">Passaporte e pontos de carimbo Estrada Real ↗</a><a href="https://institutoestradareal.com.br/servicos/" target="_blank" rel="noopener noreferrer">Serviços na Estrada Real ↗</a><a href="https://monumentobikers.com.br/memorando/" target="_blank" rel="noopener noreferrer">Orientações de viagem da Rota Biker ↗</a><Link href="/guias">Guias de preparação Pista Viva ↗</Link></div></section>
      <footer className="cd-sources"><strong>Fontes consultadas em 13 de setembro de 2026</strong><p><a href={data.source} target="_blank" rel="noopener noreferrer">Instituto Estrada Real: roteiro, 18 páginas de etapas e arquivos GPX</a> · <a href="https://monumentobikers.com.br/" target="_blank" rel="noopener noreferrer">Rota Biker: monumentos, mapa e memorando</a>.</p><p>As notas de piso preservam incertezas e divergências entre páginas. “Piso a confirmar” inclui etapas indicadas como terra no resumo, sem delimitação detalhada. Este guia não fornece alertas de mudança de piso em tempo real nem certifica a liberação para motos. Não há vínculo institucional anunciado com as fontes.</p></footer>
    </div>
  </div>;
}
